@isTest
/** ------------------------------------------------------------------------------------------------------
 * @Description Second Test class for ECO_GroupedBatchProjectTask_Rollup.cls
 * NOTE this has to be broken into multiple test classes since it appears that SFDC won't allow  more than 
 * 		3 batch initiations per test class 
 *
 * @Author      NTT Data - Deborah Orth
 * @Date        Septermber 2016
 *-----------------------------------------------------------------------------------------------------*/
private class ECO_GroupedBatch_KickoffTest2 {
	//deprecated see ECO_GroupedBatch_KickoffTest.cls DJO 1/12/2017
}