/** ------------------------------------------------------------------------------------------------------
* @Description Test class for ECO_Financial_Security service class
*
* @Author      NTT Data - Priya Parepalli
* @Date        08/08/2016
*-----------------------------------------------------------------------------------------------------*/
@isTest
private class ECO_Financial_Security_Test {

	static testmethod void testController(){
		
		Test.startTest();
		
		ECO_Financial_Security con = new ECO_Financial_Security();
		
		Test.stopTest();
	}
}