public without sharing class ECO_Constants {
	public static final String PortalMessage_NewsTickerRecordTypeName = 'NewsTicker';
	public static final String PortalMessage_AlertRecordTypeName = 'Alert';
	public static final String PortalMessage_FeedItemRecordTypeName = 'NewsFeedItem';
	public static final String PortalMessage_OpenProjectReviewMessage = 'You have an open project Review';
	
	public static final String Configuration_ApplicationRecordTypeName = 'Application';
	public static final String Configuration_ApplicationTemplateRecordTypeName = 'ApplicationTemplate';
	public static final String Configuration_ApplicationReportRecordTypeName = 'Report';
	
	public static final String Contact_PSAResourceRecordTypeName = 'PSA Resource';
	
	public static final String ProjectReview_HealthyStartRecordTypeName = 'HealthyStart';
	public static final String ProjectReview_HealthyReStartRecordTypeName = 'HealthyRestart';

	public static final String ProjectReview_BatchReviewFrequency = 'Monthly';
	
	public static final String ProjectCloseoutGenericITEmail = 'brent.kendall@nttdata.com';
	
	public static final String BulkChangeReplacementStatusPending = 'Pending';
	public static final String BulkChangeReplacementStatusSubmitted = 'Submitted';
	public static final String BulkChangeReplacementStatusWaitingforSync = 'Waiting for Sync';
	public static final String BulkChangeReplacementStatusProcessed = 'Processed';
	public static final String BulkChangeReplacementStatusError = 'Error';

	public static final String BulkChangeStatusDraft = 'Draft';
	public static final String BulkChangeStatusSubmitted = 'Submitted';
	public static final String BulkChangeStatusApproved = 'Approved';
	public static final String BulkChangeStatusRejected = 'Rejected';
	public static final String BulkChangeStatusExecuted = 'Executed';
	public static final String BulkChangeStatusResent = 'Resent';

	public static final String PortalMessage_AlertRecordTypeDeveloperName = 'Alert';
	public static final String ProjectReview_HealthyStartRecordTypeDeveloperName = 'HealthyStart';
	public static final String ProjectReview_HealthyReStartRecordTypeDeveloperName = 'HealthyRestart';

}