@isTest
/** ------------------------------------------------------------------------------------------------------
 * @Description The test class is  now deprecated, see the following classes:
 *				ECO_Mapper_ProjectTest
 *				ECO_Mapper_ProjectTaskTest
 *				ECO_Mapper_BudgetHeaderTest
 *				ECO_Mapper_BudgetTaskTest
 *				ECO_Mapper_EarnedValueTaskTest
 *				ECO_Mapper_EarnedValueSnapshotTest
 *				ECO_Mapper_WeeklyRollupEntryTest
 *
 * @Author      NTT Data - Deborah Orth
 * @Date        September 2016
 *-----------------------------------------------------------------------------------------------------*/
private class ECO_Mapper_Test {}