public class GFA_ProjectSubtaskCriteria extends GFA_Criteria {
    public GFA_ProjectSubtaskCriteria() {
        PROJECT_SPONSOR_PATH = 'Library_Subtask_Version__r.Project_Sponsor__c';
        OPERATING_GROUP_PATH = 'Library_Subtask_Version__r.Operating_Group__c';
        BUSINESS_LINE_PATH = 'Library_Subtask_Version__r.Business_Line__c';
        DISCIPLINE_PATH = 'Library_Subtask_Version__r.Discipline__c';
        RISK_LEVEL_PATH = 'Library_Subtask_Version__r.Risk_Level__c';
        IMPACT_LEVEL_PATH = 'Library_Subtask_Version__r.Impact_Level__c';
        SCOPE_OF_SERVICE_PATH = 'Library_Subtask_Version__r.Scope_of_Service__c';
        PROJECT_PATH = 'Project_Task__r.Project_Phase__r.GFA_Project__c';
        CRITICAL_OVERRIDE_PATH = 'Is_Critical_Override__c';
    }
}